[[jq]]
arch = "aarch64"
git-tree-sha1 = "56036e01b55fe3544be501495bc0fa47defd26c0"
os = "macos"

    [[jq.download]]
    sha256 = "311a887803d943711e71cb8c1681d70d2a7f999a02aa989b4324a04f9ca859f1"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.aarch64-apple-darwin.tar.gz"
[[jq]]
arch = "aarch64"
git-tree-sha1 = "e4467654a5efc8379c03081939751c23fa96743f"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "5e6a43ac4067f8d6c38117dab9c6be0d7da10e55cab0cc05d064129eb07cd9d7"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.aarch64-linux-gnu.tar.gz"
[[jq]]
arch = "aarch64"
git-tree-sha1 = "426f2b27e6ab26ca7eec08e02858a4e94a351155"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "e8e09c2bf3b6298456bc31e9e5c94ad58b70e838f0531d04b9d791355565a4cd"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.aarch64-linux-musl.tar.gz"
[[jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6885e967031d472c448e719f0e7773dc43a7d3dc"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "e243e17ce4116b4b913ab8bcba8575cb605894c1dc878f54780d2ce98ef2ed38"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.armv6l-linux-gnueabihf.tar.gz"
[[jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "91f45e16c775b6c490249b3fd4bb1bcffada18ea"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "6de221cb2c61fa8a0edee4a0e2151215eac74cd024fe02aaa8ab6d75f8118d57"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.armv6l-linux-musleabihf.tar.gz"
[[jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ac82e9562f69b7803dec0948f5acbaa2410778c"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "f238d6a9a76df8ad5e6ab304a1d333f5a9946a80599c5b38b0c74dd2a67ded9a"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.armv7l-linux-gnueabihf.tar.gz"
[[jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "707eafc1661009173966c61b5cb59ccb25621e71"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "bac421cf95e5defd4efeb9879ed1494f208d5342b25c0760e59330a5e01bdcaf"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.armv7l-linux-musleabihf.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "fb13eef17b2a4bf0e8d711ce98c3b46d42ce238e"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "ddca12dcf08670fab152ece3d59e339aeab21f90c430f555e08b42710e41fa07"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.i686-linux-gnu.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "03aeb246d86424afac1ebead2267199376a11815"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "5aff50e8d5807dab850873a79ce71b0364c73295d7d2fa9950a4a040052028f1"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.i686-linux-musl.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "6cdb3547942f19aeb968f50a5f49631f8dd1b675"
os = "windows"

    [[jq.download]]
    sha256 = "f39a0438e9e7740655bb73641d3df4f75edb3244bb0ab36e1ff6eacd3cd1663a"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.i686-w64-mingw32.tar.gz"
[[jq]]
arch = "powerpc64le"
git-tree-sha1 = "a9ec8d48c124b483f9295ff2d89627e03f6804b3"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "55a1cf5abc99a47b89e5c5d6591037f9a2581926a2ba487929ee61ea87aab6a7"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "130019044f79fefb38a689fe46f40d40738fb1a1"
os = "macos"

    [[jq.download]]
    sha256 = "c7437cf3c279ea8371be3c4a7bcc1045e211f033b0d8331dd8df50e48a2fbfff"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.x86_64-apple-darwin.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "b1c3df350f51da252793033363f8f21546e754a4"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "9fffaa98621a69a2a69fae87fd4a385e33281832ac08a9fa69a35b9b71379408"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.x86_64-linux-gnu.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "253bdfe8b5ea101eb1af3517f83c782eb7664220"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "765785652c91e694b6c634226753c03926e1d8a0f55d6610e90cf2b4a5ab2007"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.x86_64-linux-musl.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "c93e8f8f194f47d470e1aca216295f80af8c8513"
os = "freebsd"

    [[jq.download]]
    sha256 = "6f872d656ee68a64d28345076963137a17d35b62555a5093f95398c6c138bae3"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.x86_64-unknown-freebsd.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "374407e2ba9e635ac98de46534aefacc2e3d90e2"
os = "windows"

    [[jq.download]]
    sha256 = "1a668da4c2993ae90a635b5b11760e727a5540ade54b45f9f6f4f05d15780d5f"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.6.0+0/jq.v1.6.0.x86_64-w64-mingw32.tar.gz"
