[[jq]]
arch = "aarch64"
git-tree-sha1 = "1b969f17a833a1ed29dc536932cd09b006f167cb"
os = "macos"

    [[jq.download]]
    sha256 = "c29100bb8c17776dfb077e4fb7a97400fe7797e7789b7a8c691206cdf8859d41"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.aarch64-apple-darwin.tar.gz"
[[jq]]
arch = "aarch64"
git-tree-sha1 = "e6ba06cf01bc66eab23c696a49b4d806ce4d7a2d"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "8c63f37fbc95cea9ef02aad6e31d24806056b3c6285720aa210fffac1d48e2f0"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.aarch64-linux-gnu.tar.gz"
[[jq]]
arch = "aarch64"
git-tree-sha1 = "8e92e75f4daf2bf4f58742b350dfe3cb7aabc8c4"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "88d89685ce34ae98f093c2d2f3e9a2f5c3de9528a8cb6cce08443f33bcbd63e0"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.aarch64-linux-musl.tar.gz"
[[jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "471d2fc65fa4261a79fa180d8203eb5c3d857267"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "6ebc30096d6eef2b9ef4685c59716d55f9f3721ec907c08801e461a14fb9ba32"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.armv6l-linux-gnueabihf.tar.gz"
[[jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa1d1a3da031223035c3d60029b9cae610f6bcf0"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "30b12b86e7879960e8058251f2b2004335b2e1b3df10e35b509608ee767dce8d"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.armv6l-linux-musleabihf.tar.gz"
[[jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c16d6bb0b23a355049d4c5db8bbe3a542f3e7e75"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "0507dc8c7b5c7976993b09c88e587f2ab182ffc889536da03f1fb78686648d14"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.armv7l-linux-gnueabihf.tar.gz"
[[jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f278494d9ef68c351e4890408b07a64328f77713"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "d56ff8f42c5983803decfa75ffce9501eab1773d49b67fc4471647850f678ab4"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.armv7l-linux-musleabihf.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "db0e71d5ae2b072826def6824f6681556238f757"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "1efc567da2b286b1d26af4b85708c790ae81125738fcca45f6f67863d2bc0937"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.i686-linux-gnu.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "f144ae556d452256bbc761d667dcf3e53ad89f2b"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "fc9a867fb315d00bd2b129a6d9d639f6d67aa8c8083faf03f230cccdd603225e"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.i686-linux-musl.tar.gz"
[[jq]]
arch = "i686"
git-tree-sha1 = "a0d3e4567012b8cb62e029994f2dad92c73192c0"
os = "windows"

    [[jq.download]]
    sha256 = "85c2f326df660e69a7a1b19b28f601fb615b1e090c86a359c11cc0732818398b"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.i686-w64-mingw32.tar.gz"
[[jq]]
arch = "powerpc64le"
git-tree-sha1 = "8c0e2b3536b5b1ec592b00e5f647f0fc682099f1"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "2d21b415e94b268c9df902e8ae99d7c286945624e4897a5a0d3931ccba428e9e"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.powerpc64le-linux-gnu.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "76534e4d82b8873694db5cf6f25e294f037ba742"
os = "macos"

    [[jq.download]]
    sha256 = "70095e294168f643daa8cbaf1f944784b1623c78444d5604b03eb0d7e19887b8"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.x86_64-apple-darwin.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "1062035f1811ac5451581a1f05f8af866917343c"
libc = "glibc"
os = "linux"

    [[jq.download]]
    sha256 = "28f3692a079561bfc988b6966f15e5880f971529b4a160be44bbe5d70e4e0c4c"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.x86_64-linux-gnu.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "b4f17c70b57de92f0353e947001c518bcbb85982"
libc = "musl"
os = "linux"

    [[jq.download]]
    sha256 = "01642d7896f59a9b2df5d17211c8136e84c7c9225a0214c41e894cda28192b64"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.x86_64-linux-musl.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "8d87cd8ee15b3cca01160a5a7e01d34a6123ecc1"
os = "freebsd"

    [[jq.download]]
    sha256 = "4f1fb7e0060618e7af7943ddea94ad5c52fc578beb6f013412dcfe72585ba178"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[jq]]
arch = "x86_64"
git-tree-sha1 = "8c3936dd362bbe33eaa161962ff7526d9238886c"
os = "windows"

    [[jq.download]]
    sha256 = "1c6606c9fa1e28999fc19787671a1ca2acb7a3bf580da4dcf7c96b479c5d692e"
    url = "https://github.com/JuliaBinaryWrappers/jq_jll.jl/releases/download/jq-v1.7.1+0/jq.v1.7.1.x86_64-w64-mingw32.tar.gz"
