# Autogenerated wrapper script for jq_jll for x86_64-w64-mingw32
export jq

JLLWrappers.@generate_wrapper_header("jq")
JLLWrappers.@declare_executable_product(jq)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        jq,
        "bin\\jq.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
